// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: WiFiForLVGLv1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_InitScreen
void ui_InitScreen_screen_init(void);
lv_obj_t * ui_InitScreen;
lv_obj_t * ui_ContainerInitScreen;
lv_obj_t * ui_ContainerInitButton;
void ui_event_ImgButtonInitRight(lv_event_t * e);
lv_obj_t * ui_ImgButtonInitRight;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_ImageLogoUD;
lv_obj_t * ui_ImageFotoG2EJ;
lv_obj_t * ui_ImageAIoT;
lv_obj_t * ui_ImageAIoT1;


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_ContainerMainScreen;
lv_obj_t * ui_ContainerMainButton;
lv_obj_t * ui_PanelMainButton;
void ui_event_ImgButtonMailLeft(lv_event_t * e);
lv_obj_t * ui_ImgButtonMailLeft;
void ui_event_ImgButtonMailRight(lv_event_t * e);
lv_obj_t * ui_ImgButtonMailRight;
void ui_event_ButtonConnect(lv_event_t * e);
lv_obj_t * ui_ButtonConnect;
lv_obj_t * ui_LabelConnect;
void ui_event_ButtonReScan(lv_event_t * e);
lv_obj_t * ui_ButtonReScan;
lv_obj_t * ui_LabelReScan;
lv_obj_t * ui_PanelScreenConnecting;
lv_obj_t * ui_ContainerWiFIKeyboard;
lv_obj_t * ui_PanelWiFIKeyboard;
lv_obj_t * ui_ContainerWiFi;
lv_obj_t * ui_LabelMainSSID;
lv_obj_t * ui_LabelMainPassword;
lv_obj_t * ui_DropDownSSID;
void ui_event_TextAreaWiFiPasword(lv_event_t * e);
lv_obj_t * ui_TextAreaWiFiPasword;
lv_obj_t * ui_ContainerKeyboard;
void ui_event_Keyboard(lv_event_t * e);
lv_obj_t * ui_Keyboard;
lv_obj_t * ui_LabelConnecting;


// SCREEN: ui_ConnectedScreen
void ui_ConnectedScreen_screen_init(void);
lv_obj_t * ui_ConnectedScreen;
lv_obj_t * ui_ContainerConnectedScreen;
lv_obj_t * ui_ContainerConnectedButon;
lv_obj_t * ui_PanelConnectedButon;
void ui_event_ImgButtonConnectedLeft(lv_event_t * e);
lv_obj_t * ui_ImgButtonConnectedLeft;
void ui_event_ImgButtonConnectedRight(lv_event_t * e);
lv_obj_t * ui_ImgButtonConnectedRight;
lv_obj_t * ui_PanelConnectedConnecting;
lv_obj_t * ui_ContainerLabel;
lv_obj_t * ui_PanelLabel;
lv_obj_t * ui_LabelDNS;
lv_obj_t * ui_LabelMAC;
lv_obj_t * ui_LabelIP;
lv_obj_t * ui_LabelSSID;
lv_obj_t * ui_LabelWiFiSSID;
lv_obj_t * ui_LabelWiFiIP;
lv_obj_t * ui_LabelWiFiDNS;
lv_obj_t * ui_LabelWiFiMAC;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_der_x[1] = {&ui_img_der_032x032_png};
const lv_img_dsc_t * ui_imgset_izq_x[1] = {&ui_img_izq_032x032_png};
const lv_img_dsc_t * ui_imgset_burbujas_x[1] = {&ui_img_burbujas_080x080_png};
const lv_img_dsc_t * ui_imgset_foto_g2ej_x[1] = {&ui_img_foto_g2ej_064x064_png};
const lv_img_dsc_t * ui_imgset_logo_aiot_157x[1] = {&ui_img_logo_aiot_157x105_png};
const lv_img_dsc_t * ui_imgset_logo_g2ej_105x[1] = {&ui_img_logo_g2ej_105x156_png};
const lv_img_dsc_t * ui_imgset_logo_ud_fjdc_058x[1] = {&ui_img_logo_ud_fjdc_058x090_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ImgButtonInitRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_ImgButtonMailLeft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_InitScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_InitScreen_screen_init);
    }
}
void ui_event_ImgButtonMailRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConnectedScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ConnectedScreen_screen_init);
    }
}
void ui_event_ButtonConnect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ConnectToRouter(e);
    }
}
void ui_event_ButtonReScan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ReScanWiFiSSID(e);
    }
}
void ui_event_TextAreaWiFiPasword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        ShowKeyBoard(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        HideKeyBoard(e);
    }
    if(event_code == LV_EVENT_READY) {
        HideKeyBoard(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        ShowKeyBoard(e);
    }
}
void ui_event_Keyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        ShowKeyBoard(e);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        HideKeyBoard(e);
    }
    if(event_code == LV_EVENT_READY) {
        HideKeyBoard(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        ShowKeyBoard(e);
    }
}
void ui_event_ImgButtonConnectedLeft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_ImgButtonConnectedRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_InitScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_InitScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_InitScreen_screen_init();
    ui_MainScreen_screen_init();
    ui_ConnectedScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_InitScreen);
}
