// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: WiFiForLVGLv1

#ifndef _WIFIFORLVGLV1_UI_H
#define _WIFIFORLVGLV1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_InitScreen
void ui_InitScreen_screen_init(void);
extern lv_obj_t * ui_InitScreen;
extern lv_obj_t * ui_ContainerInitScreen;
extern lv_obj_t * ui_ContainerInitButton;
void ui_event_ImgButtonInitRight(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonInitRight;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_ImageLogoUD;
extern lv_obj_t * ui_ImageFotoG2EJ;
extern lv_obj_t * ui_ImageAIoT;
extern lv_obj_t * ui_ImageAIoT1;
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_ContainerMainScreen;
extern lv_obj_t * ui_ContainerMainButton;
extern lv_obj_t * ui_PanelMainButton;
void ui_event_ImgButtonMailLeft(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonMailLeft;
void ui_event_ImgButtonMailRight(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonMailRight;
void ui_event_ButtonConnect(lv_event_t * e);
extern lv_obj_t * ui_ButtonConnect;
extern lv_obj_t * ui_LabelConnect;
void ui_event_ButtonReScan(lv_event_t * e);
extern lv_obj_t * ui_ButtonReScan;
extern lv_obj_t * ui_LabelReScan;
extern lv_obj_t * ui_PanelScreenConnecting;
extern lv_obj_t * ui_ContainerWiFIKeyboard;
extern lv_obj_t * ui_PanelWiFIKeyboard;
extern lv_obj_t * ui_ContainerWiFi;
extern lv_obj_t * ui_LabelMainSSID;
extern lv_obj_t * ui_LabelMainPassword;
extern lv_obj_t * ui_DropDownSSID;
void ui_event_TextAreaWiFiPasword(lv_event_t * e);
extern lv_obj_t * ui_TextAreaWiFiPasword;
extern lv_obj_t * ui_ContainerKeyboard;
void ui_event_Keyboard(lv_event_t * e);
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui_LabelConnecting;
// SCREEN: ui_ConnectedScreen
void ui_ConnectedScreen_screen_init(void);
extern lv_obj_t * ui_ConnectedScreen;
extern lv_obj_t * ui_ContainerConnectedScreen;
extern lv_obj_t * ui_ContainerConnectedButon;
extern lv_obj_t * ui_PanelConnectedButon;
void ui_event_ImgButtonConnectedLeft(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonConnectedLeft;
void ui_event_ImgButtonConnectedRight(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonConnectedRight;
extern lv_obj_t * ui_PanelConnectedConnecting;
extern lv_obj_t * ui_ContainerLabel;
extern lv_obj_t * ui_PanelLabel;
extern lv_obj_t * ui_LabelDNS;
extern lv_obj_t * ui_LabelMAC;
extern lv_obj_t * ui_LabelIP;
extern lv_obj_t * ui_LabelSSID;
extern lv_obj_t * ui_LabelWiFiSSID;
extern lv_obj_t * ui_LabelWiFiIP;
extern lv_obj_t * ui_LabelWiFiDNS;
extern lv_obj_t * ui_LabelWiFiMAC;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_burbujas_080x080_png);    // assets\Burbujas_080x080.png
LV_IMG_DECLARE(ui_img_der_032x032_png);    // assets\Der_032x032.png
LV_IMG_DECLARE(ui_img_logo_ud_fjdc_058x090_png);    // assets\Logo_ud_FJdC_058x090.png
LV_IMG_DECLARE(ui_img_foto_g2ej_064x064_png);    // assets\Foto_G2EJ_064x064.png
LV_IMG_DECLARE(ui_img_logo_aiot_157x105_png);    // assets\Logo_AIoT_157x105.png
LV_IMG_DECLARE(ui_img_logo_g2ej_105x156_png);    // assets\Logo_G2EJ_105x156.png
LV_IMG_DECLARE(ui_img_izq_032x032_png);    // assets\Izq_032x032.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
