// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: WiFiForLVGLv1

#include "ui.h"

void ConnectToRouter(lv_event_t * e)
{
	// Your code here
}

void ReScanWiFiSSID(lv_event_t * e)
{
	// Your code here
}

void ShowKeyBoard(lv_event_t * e)
{
	// Your code here
}

void HideKeyBoard(lv_event_t * e)
{
	// Your code here
}
