// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: WiFiForLVGLv1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ConnectToRouter(lv_event_t * e);
void ReScanWiFiSSID(lv_event_t * e);
void ShowKeyBoard(lv_event_t * e);
void HideKeyBoard(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
