// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: WiFiForLVGLv1

#include "../ui.h"

void ui_ConnectedScreen_screen_init(void)
{
    ui_ConnectedScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ConnectedScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerConnectedScreen = lv_obj_create(ui_ConnectedScreen);
    lv_obj_remove_style_all(ui_ContainerConnectedScreen);
    lv_obj_set_width(ui_ContainerConnectedScreen, 480);
    lv_obj_set_height(ui_ContainerConnectedScreen, 320);
    lv_obj_set_align(ui_ContainerConnectedScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerConnectedScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerConnectedButon = lv_obj_create(ui_ContainerConnectedScreen);
    lv_obj_remove_style_all(ui_ContainerConnectedButon);
    lv_obj_set_height(ui_ContainerConnectedButon, 50);
    lv_obj_set_width(ui_ContainerConnectedButon, lv_pct(95));
    lv_obj_set_x(ui_ContainerConnectedButon, 0);
    lv_obj_set_y(ui_ContainerConnectedButon, -122);
    lv_obj_set_align(ui_ContainerConnectedButon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerConnectedButon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelConnectedButon = lv_obj_create(ui_ContainerConnectedButon);
    lv_obj_set_width(ui_PanelConnectedButon, lv_pct(100));
    lv_obj_set_height(ui_PanelConnectedButon, lv_pct(100));
    lv_obj_set_align(ui_PanelConnectedButon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelConnectedButon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelConnectedButon, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelConnectedButon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelConnectedButon, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelConnectedButon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonConnectedLeft = lv_imgbtn_create(ui_PanelConnectedButon);
    lv_imgbtn_set_src(ui_ImgButtonConnectedLeft, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_izq_032x032_png, NULL);
    lv_obj_set_width(ui_ImgButtonConnectedLeft, 32);
    lv_obj_set_height(ui_ImgButtonConnectedLeft, 32);
    lv_obj_set_x(ui_ImgButtonConnectedLeft, -180);
    lv_obj_set_y(ui_ImgButtonConnectedLeft, 0);
    lv_obj_set_align(ui_ImgButtonConnectedLeft, LV_ALIGN_CENTER);

    ui_ImgButtonConnectedRight = lv_imgbtn_create(ui_PanelConnectedButon);
    lv_imgbtn_set_src(ui_ImgButtonConnectedRight, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_der_032x032_png, NULL);
    lv_obj_set_width(ui_ImgButtonConnectedRight, 32);
    lv_obj_set_height(ui_ImgButtonConnectedRight, 32);
    lv_obj_set_x(ui_ImgButtonConnectedRight, 180);
    lv_obj_set_y(ui_ImgButtonConnectedRight, 0);
    lv_obj_set_align(ui_ImgButtonConnectedRight, LV_ALIGN_CENTER);

    ui_PanelConnectedConnecting = lv_obj_create(ui_ContainerConnectedButon);
    lv_obj_set_width(ui_PanelConnectedConnecting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelConnectedConnecting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PanelConnectedConnecting, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelConnectedConnecting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelConnectedConnecting, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelConnectedConnecting, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelConnectedConnecting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLabel = lv_obj_create(ui_ContainerConnectedScreen);
    lv_obj_remove_style_all(ui_ContainerLabel);
    lv_obj_set_width(ui_ContainerLabel, lv_pct(95));
    lv_obj_set_height(ui_ContainerLabel, lv_pct(74));
    lv_obj_set_x(ui_ContainerLabel, 0);
    lv_obj_set_y(ui_ContainerLabel, 27);
    lv_obj_set_align(ui_ContainerLabel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelLabel = lv_obj_create(ui_ContainerLabel);
    lv_obj_set_width(ui_PanelLabel, lv_pct(100));
    lv_obj_set_height(ui_PanelLabel, lv_pct(100));
    lv_obj_set_align(ui_PanelLabel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelLabel, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelLabel, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDNS = lv_label_create(ui_PanelLabel);
    lv_obj_set_width(ui_LabelDNS, 145);
    lv_obj_set_height(ui_LabelDNS, 15);
    lv_obj_set_x(ui_LabelDNS, -130);
    lv_obj_set_y(ui_LabelDNS, lv_pct(12));
    lv_obj_set_align(ui_LabelDNS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDNS, "Direccion DNS.:");

    ui_LabelMAC = lv_label_create(ui_PanelLabel);
    lv_obj_set_width(ui_LabelMAC, 145);
    lv_obj_set_height(ui_LabelMAC, 15);
    lv_obj_set_x(ui_LabelMAC, -130);
    lv_obj_set_y(ui_LabelMAC, lv_pct(36));
    lv_obj_set_align(ui_LabelMAC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMAC, "Direccion MAC.:");

    ui_LabelIP = lv_label_create(ui_PanelLabel);
    lv_obj_set_width(ui_LabelIP, 145);
    lv_obj_set_height(ui_LabelIP, 15);
    lv_obj_set_x(ui_LabelIP, -130);
    lv_obj_set_y(ui_LabelIP, lv_pct(-12));
    lv_obj_set_align(ui_LabelIP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIP, "Direccion IP.:");

    ui_LabelSSID = lv_label_create(ui_PanelLabel);
    lv_obj_set_width(ui_LabelSSID, 145);
    lv_obj_set_height(ui_LabelSSID, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_LabelSSID, -130);
    lv_obj_set_y(ui_LabelSSID, lv_pct(-36));
    lv_obj_set_align(ui_LabelSSID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSSID, "Conectado a la Red WiFi (SSID).:");

    ui_LabelWiFiSSID = lv_label_create(ui_PanelLabel);
    lv_obj_set_width(ui_LabelWiFiSSID, 260);
    lv_obj_set_height(ui_LabelWiFiSSID, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_LabelWiFiSSID, 80);
    lv_obj_set_y(ui_LabelWiFiSSID, lv_pct(-36));
    lv_obj_set_align(ui_LabelWiFiSSID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWiFiSSID, "SSID");

    ui_LabelWiFiIP = lv_label_create(ui_PanelLabel);
    lv_obj_set_width(ui_LabelWiFiIP, 260);
    lv_obj_set_height(ui_LabelWiFiIP, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_LabelWiFiIP, 80);
    lv_obj_set_y(ui_LabelWiFiIP, lv_pct(-12));
    lv_obj_set_align(ui_LabelWiFiIP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWiFiIP, "xxx.xxx.xxx.xxx");

    ui_LabelWiFiDNS = lv_label_create(ui_PanelLabel);
    lv_obj_set_width(ui_LabelWiFiDNS, 260);
    lv_obj_set_height(ui_LabelWiFiDNS, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_LabelWiFiDNS, 80);
    lv_obj_set_y(ui_LabelWiFiDNS, lv_pct(12));
    lv_obj_set_align(ui_LabelWiFiDNS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWiFiDNS, "xxx.xxx.xxx.xxx");

    ui_LabelWiFiMAC = lv_label_create(ui_PanelLabel);
    lv_obj_set_width(ui_LabelWiFiMAC, 260);
    lv_obj_set_height(ui_LabelWiFiMAC, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_LabelWiFiMAC, 80);
    lv_obj_set_y(ui_LabelWiFiMAC, lv_pct(36));
    lv_obj_set_align(ui_LabelWiFiMAC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWiFiMAC, "xx:xx:xx:xx:xx:xx");

    lv_obj_add_event_cb(ui_ImgButtonConnectedLeft, ui_event_ImgButtonConnectedLeft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonConnectedRight, ui_event_ImgButtonConnectedRight, LV_EVENT_ALL, NULL);

}
