// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: WiFiForLVGLv1

#include "../ui.h"

void ui_InitScreen_screen_init(void)
{
    ui_InitScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_InitScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerInitScreen = lv_obj_create(ui_InitScreen);
    lv_obj_remove_style_all(ui_ContainerInitScreen);
    lv_obj_set_width(ui_ContainerInitScreen, 480);
    lv_obj_set_height(ui_ContainerInitScreen, 320);
    lv_obj_set_align(ui_ContainerInitScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerInitScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ContainerInitScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerInitScreen, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerInitScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ContainerInitScreen, &ui_img_burbujas_080x080_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ContainerInitScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_ContainerInitScreen, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerInitButton = lv_obj_create(ui_ContainerInitScreen);
    lv_obj_remove_style_all(ui_ContainerInitButton);
    lv_obj_set_height(ui_ContainerInitButton, 50);
    lv_obj_set_width(ui_ContainerInitButton, lv_pct(95));
    lv_obj_set_x(ui_ContainerInitButton, 0);
    lv_obj_set_y(ui_ContainerInitButton, -122);
    lv_obj_set_align(ui_ContainerInitButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerInitButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButtonInitRight = lv_imgbtn_create(ui_ContainerInitButton);
    lv_imgbtn_set_src(ui_ImgButtonInitRight, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_der_032x032_png, NULL);
    lv_obj_set_width(ui_ImgButtonInitRight, 32);
    lv_obj_set_height(ui_ImgButtonInitRight, 32);
    lv_obj_set_x(ui_ImgButtonInitRight, 200);
    lv_obj_set_y(ui_ImgButtonInitRight, 0);
    lv_obj_set_align(ui_ImgButtonInitRight, LV_ALIGN_CENTER);

    ui_Panel1 = lv_obj_create(ui_ContainerInitButton);
    lv_obj_set_width(ui_Panel1, lv_pct(70));
    lv_obj_set_height(ui_Panel1, lv_pct(100));
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "ERNESTO JOSE GUERRERO GONZALEZ\nAIoT Transitorios Hidraulicos");
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageLogoUD = lv_img_create(ui_ContainerInitScreen);
    lv_img_set_src(ui_ImageLogoUD, &ui_img_logo_ud_fjdc_058x090_png);
    lv_obj_set_width(ui_ImageLogoUD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageLogoUD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageLogoUD, -200);
    lv_obj_set_y(ui_ImageLogoUD, -110);
    lv_obj_set_align(ui_ImageLogoUD, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLogoUD, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLogoUD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageFotoG2EJ = lv_img_create(ui_ContainerInitScreen);
    lv_img_set_src(ui_ImageFotoG2EJ, &ui_img_foto_g2ej_064x064_png);
    lv_obj_set_width(ui_ImageFotoG2EJ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageFotoG2EJ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageFotoG2EJ, -200);
    lv_obj_set_y(ui_ImageFotoG2EJ, 110);
    lv_obj_set_align(ui_ImageFotoG2EJ, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageFotoG2EJ, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageFotoG2EJ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageAIoT = lv_img_create(ui_ContainerInitScreen);
    lv_img_set_src(ui_ImageAIoT, &ui_img_logo_aiot_157x105_png);
    lv_obj_set_width(ui_ImageAIoT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAIoT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAIoT, 152);
    lv_obj_set_y(ui_ImageAIoT, 99);
    lv_obj_set_align(ui_ImageAIoT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAIoT, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAIoT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageAIoT1 = lv_img_create(ui_ContainerInitScreen);
    lv_img_set_src(ui_ImageAIoT1, &ui_img_logo_g2ej_105x156_png);
    lv_obj_set_width(ui_ImageAIoT1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAIoT1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageAIoT1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageAIoT1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAIoT1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ImgButtonInitRight, ui_event_ImgButtonInitRight, LV_EVENT_ALL, NULL);

}
