// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: WiFiForLVGLv1

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerMainScreen = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_ContainerMainScreen);
    lv_obj_set_width(ui_ContainerMainScreen, 480);
    lv_obj_set_height(ui_ContainerMainScreen, 320);
    lv_obj_set_align(ui_ContainerMainScreen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerMainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_img_opa(ui_ContainerMainScreen, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_ContainerMainScreen, true, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ContainerMainButton = lv_obj_create(ui_ContainerMainScreen);
    lv_obj_remove_style_all(ui_ContainerMainButton);
    lv_obj_set_height(ui_ContainerMainButton, 50);
    lv_obj_set_width(ui_ContainerMainButton, lv_pct(95));
    lv_obj_set_x(ui_ContainerMainButton, 0);
    lv_obj_set_y(ui_ContainerMainButton, -122);
    lv_obj_set_align(ui_ContainerMainButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerMainButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContainerMainButton, lv_color_hex(0x727A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerMainButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelMainButton = lv_obj_create(ui_ContainerMainButton);
    lv_obj_set_height(ui_PanelMainButton, 50);
    lv_obj_set_width(ui_PanelMainButton, lv_pct(100));
    lv_obj_set_align(ui_PanelMainButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMainButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelMainButton, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMainButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelMainButton, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelMainButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonMailLeft = lv_imgbtn_create(ui_PanelMainButton);
    lv_imgbtn_set_src(ui_ImgButtonMailLeft, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_izq_032x032_png, NULL);
    lv_obj_set_width(ui_ImgButtonMailLeft, 32);
    lv_obj_set_height(ui_ImgButtonMailLeft, 32);
    lv_obj_set_x(ui_ImgButtonMailLeft, -180);
    lv_obj_set_y(ui_ImgButtonMailLeft, 0);
    lv_obj_set_align(ui_ImgButtonMailLeft, LV_ALIGN_CENTER);

    ui_ImgButtonMailRight = lv_imgbtn_create(ui_PanelMainButton);
    lv_imgbtn_set_src(ui_ImgButtonMailRight, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_der_032x032_png, NULL);
    lv_obj_set_width(ui_ImgButtonMailRight, 32);
    lv_obj_set_height(ui_ImgButtonMailRight, 32);
    lv_obj_set_x(ui_ImgButtonMailRight, 180);
    lv_obj_set_y(ui_ImgButtonMailRight, 0);
    lv_obj_set_align(ui_ImgButtonMailRight, LV_ALIGN_CENTER);

    ui_ButtonConnect = lv_btn_create(ui_PanelMainButton);
    lv_obj_set_width(ui_ButtonConnect, 100);
    lv_obj_set_height(ui_ButtonConnect, 35);
    lv_obj_set_x(ui_ButtonConnect, -100);
    lv_obj_set_y(ui_ButtonConnect, 0);
    lv_obj_set_align(ui_ButtonConnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelConnect = lv_label_create(ui_ButtonConnect);
    lv_obj_set_width(ui_LabelConnect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelConnect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelConnect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelConnect, "Connect");

    ui_ButtonReScan = lv_btn_create(ui_PanelMainButton);
    lv_obj_set_width(ui_ButtonReScan, 100);
    lv_obj_set_height(ui_ButtonReScan, 35);
    lv_obj_set_x(ui_ButtonReScan, 100);
    lv_obj_set_y(ui_ButtonReScan, 0);
    lv_obj_set_align(ui_ButtonReScan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonReScan, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonReScan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelReScan = lv_label_create(ui_ButtonReScan);
    lv_obj_set_width(ui_LabelReScan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelReScan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelReScan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelReScan, "Re-Scan");

    ui_PanelScreenConnecting = lv_obj_create(ui_PanelMainButton);
    lv_obj_set_width(ui_PanelScreenConnecting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelScreenConnecting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PanelScreenConnecting, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScreenConnecting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelScreenConnecting, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelScreenConnecting, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScreenConnecting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerWiFIKeyboard = lv_obj_create(ui_ContainerMainScreen);
    lv_obj_remove_style_all(ui_ContainerWiFIKeyboard);
    lv_obj_set_width(ui_ContainerWiFIKeyboard, lv_pct(95));
    lv_obj_set_height(ui_ContainerWiFIKeyboard, lv_pct(74));
    lv_obj_set_x(ui_ContainerWiFIKeyboard, 0);
    lv_obj_set_y(ui_ContainerWiFIKeyboard, 28);
    lv_obj_set_align(ui_ContainerWiFIKeyboard, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerWiFIKeyboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelWiFIKeyboard = lv_obj_create(ui_ContainerWiFIKeyboard);
    lv_obj_set_width(ui_PanelWiFIKeyboard, lv_pct(100));
    lv_obj_set_height(ui_PanelWiFIKeyboard, lv_pct(100));
    lv_obj_set_align(ui_PanelWiFIKeyboard, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWiFIKeyboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelWiFIKeyboard, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWiFIKeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelWiFIKeyboard, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelWiFIKeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerWiFi = lv_obj_create(ui_PanelWiFIKeyboard);
    lv_obj_remove_style_all(ui_ContainerWiFi);
    lv_obj_set_width(ui_ContainerWiFi, lv_pct(100));
    lv_obj_set_height(ui_ContainerWiFi, lv_pct(35));
    lv_obj_set_x(ui_ContainerWiFi, 0);
    lv_obj_set_y(ui_ContainerWiFi, lv_pct(-35));
    lv_obj_set_align(ui_ContainerWiFi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelMainSSID = lv_label_create(ui_ContainerWiFi);
    lv_obj_set_width(ui_LabelMainSSID, 110);
    lv_obj_set_height(ui_LabelMainSSID, 15);
    lv_obj_set_x(ui_LabelMainSSID, -150);
    lv_obj_set_y(ui_LabelMainSSID, lv_pct(-25));
    lv_obj_set_align(ui_LabelMainSSID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMainSSID, "WiFi SSID");

    ui_LabelMainPassword = lv_label_create(ui_ContainerWiFi);
    lv_obj_set_width(ui_LabelMainPassword, 110);
    lv_obj_set_height(ui_LabelMainPassword, 15);
    lv_obj_set_x(ui_LabelMainPassword, -150);
    lv_obj_set_y(ui_LabelMainPassword, lv_pct(25));
    lv_obj_set_align(ui_LabelMainPassword, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMainPassword, "WiFi Password");

    ui_DropDownSSID = lv_dropdown_create(ui_ContainerWiFi);
    lv_dropdown_set_options(ui_DropDownSSID, "");
    lv_obj_set_width(ui_DropDownSSID, 300);
    lv_obj_set_height(ui_DropDownSSID, lv_pct(50));
    lv_obj_set_x(ui_DropDownSSID, 60);
    lv_obj_set_y(ui_DropDownSSID, lv_pct(-25));
    lv_obj_set_align(ui_DropDownSSID, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropDownSSID, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_TextAreaWiFiPasword = lv_textarea_create(ui_ContainerWiFi);
    lv_obj_set_width(ui_TextAreaWiFiPasword, 300);
    lv_obj_set_height(ui_TextAreaWiFiPasword, lv_pct(50));
    lv_obj_set_x(ui_TextAreaWiFiPasword, 60);
    lv_obj_set_y(ui_TextAreaWiFiPasword, lv_pct(25));
    lv_obj_set_align(ui_TextAreaWiFiPasword, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaWiFiPasword, 128);
    lv_textarea_set_text(ui_TextAreaWiFiPasword, "11291104BG397");
    lv_textarea_set_placeholder_text(ui_TextAreaWiFiPasword, "Enter Password");
    lv_textarea_set_password_mode(ui_TextAreaWiFiPasword, true);



    ui_ContainerKeyboard = lv_obj_create(ui_PanelWiFIKeyboard);
    lv_obj_remove_style_all(ui_ContainerKeyboard);
    lv_obj_set_width(ui_ContainerKeyboard, lv_pct(100));
    lv_obj_set_height(ui_ContainerKeyboard, lv_pct(65));
    lv_obj_set_x(ui_ContainerKeyboard, 0);
    lv_obj_set_y(ui_ContainerKeyboard, lv_pct(20));
    lv_obj_set_align(ui_ContainerKeyboard, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerKeyboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard = lv_keyboard_create(ui_ContainerKeyboard);
    lv_obj_set_width(ui_Keyboard, lv_pct(100));
    lv_obj_set_height(ui_Keyboard, lv_pct(100));
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Keyboard, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Keyboard, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Keyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelConnecting = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelConnecting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelConnecting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelConnecting, 25);
    lv_obj_set_y(ui_LabelConnecting, -9);
    lv_obj_set_align(ui_LabelConnecting, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelConnecting, "Connecting.............");
    lv_obj_add_flag(ui_LabelConnecting, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelConnecting, lv_color_hex(0xE10E0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelConnecting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButtonMailLeft, ui_event_ImgButtonMailLeft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonMailRight, ui_event_ImgButtonMailRight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonConnect, ui_event_ButtonConnect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonReScan, ui_event_ButtonReScan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaWiFiPasword, ui_event_TextAreaWiFiPasword, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard, ui_TextAreaWiFiPasword);
    lv_obj_add_event_cb(ui_Keyboard, ui_event_Keyboard, LV_EVENT_ALL, NULL);

}
